name: vid
description: A minimal vi-like text editor for the terminal written in Dart
version: 0.1.0
homepage: https://github.com/erf/vid

environment:
  sdk: ^3.8.0

dependencies:
  characters: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  http: ^1.4.0
